### PR TITLE
Create SECURITY.md# Security Policy  ## Supported Versions  Use this …

### PR DESCRIPTION
**Pull request by ijunxyz123**
…section to tell people about which versions of your project are currently being supported with security updates.  | Version | Supported          | | ------- | ------------------ | | 5.1.x   | :white_check_mark: | | 5.0.x   | :x:                | | 4.0.x   | :white_check_mark: | | < 4.0   | :x:                |  ## Reporting a Vulnerability  Use this section to tell people how to report a vulnerability.  Tell them where to go, how often they can expect to get an update on a reported vulnerability, what to expect if the vulnerability is accepted or declined, etc.

# Description of Changes
_Summarize the changes you made as part of this pull request._# Security Policy

## Supported Versions

Use this section to tell people about which versions of your project are
currently being supported with security updates.

| Version | Supported          |
| ------- | ------------------ |
| 5.1.x   | :white_check_mark: |
| 5.0.x   | :x:                |
| 4.0.x   | :white_check_mark: |
| < 4.0   | :x:                |

## Reporting a Vulnerability

Use this section to tell people how to report a vulnerability.

Tell them where to go, how often they can expect to get an update on a
reported vulnerability, what to expect if the vulnerability is accepted or
declined, etc.

# Related Issue(s)
_Link the GitHub/GitLab/JIRA issues that are related to this PR._

# Acceptance Criteria

_Testing and documentation do not need to be complete in order for this PR to be approved. However, tracking issues must be opened for missing testing/documentation._

New testing and documentation issues can be opened under [`devfile/api/issues`](https://github.com/devfile/api/issues).

You can check the respective criteria below if either of the following is true:
- There is a separate tracking issue opened and that issue is linked in this PR.
- Testing/documentation updates are contained within this PR.

If criteria is left unchecked please provide an explanation why.

- [x] Unit/Functional tests

  

- [x] [QE Integration test](https://github.com/devfile/integration-tests)

  

- [ ] Documentation

   

- [x] Client Impact

  

# Tests Performed
_Explain what tests you personally ran to ensure the changes are functioning as expected._

# How To Test
_Instructions for the reviewer on how to test your changes._

# Notes To Reviewer
_Any notes you would like to include for the reviewer._

### CODE REVIEW

**Comment by thepetk** [comment]
Closing as duplicate of https://github.com/devfile/api/pull/1627

**Comment by albertanastasia** [comment]
ijunxyz123:patch-2

**Comment by albertanastasia** [comment]
> …section to tell people about which versions of your project are currently being supported with security updates. | Version | Supported | | ------- | ------------------ | | 5.1.x | ✅ | | 5.0.x | ❌ | | 4.0.x | ✅ | | < 4.0 | ❌ | ## Reporting a Vulnerability Use this section to tell people how to report a vulnerability. Tell them where to go, how often they can expect to get an update on a reported vulnerability, what to expect if the vulnerability is accepted or declined, etc.
> 
> # Description of Changes
> _Summarize the changes you made as part of this pull request._# Security Policy
> 
> ## Supported Versions
> Use this section to tell people about which versions of your project are currently being supported with security updates.
> 
> Version	Supported
> 5.1.x	✅
> 5.0.x	❌
> 4.0.x	✅
> < 4.0	❌
> ## Reporting a Vulnerability
> Use this section to tell people how to report a vulnerability.
> 
> Tell them where to go, how often they can expect to get an update on a reported vulnerability, what to expect if the vulnerability is accepted or declined, etc.
> 
> # Related Issue(s)
> _Link the GitHub/GitLab/JIRA issues that are related to this PR._
> 
> # Acceptance Criteria
> _Testing and documentation do not need to be complete in order for this PR to be approved. However, tracking issues must be opened for missing testing/documentation._
> 
> New testing and documentation issues can be opened under [`devfile/api/issues`](https://github.com/devfile/api/issues).
> 
> You can check the respective criteria below if either of the following is true:
> 
> * There is a separate tracking issue opened and that issue is linked in this PR.
> * Testing/documentation updates are contained within this PR.
> 
> If criteria is left unchecked please provide an explanation why.
> 
> * [x]  Unit/Functional tests
> * [x]  [QE Integration test](https://github.com/devfile/integration-tests)
> * [ ]  Documentation
> * [x]  Client Impact
> 
> # Tests Performed
> _Explain what tests you personally ran to ensure the changes are functioning as expected._
> 
> # How To Test
> _Instructions for the reviewer on how to test your changes._
> 
> # Notes To Reviewer
> _Any notes you would like to include for the reviewer._

ijunxyz123:patch-2

**Comment by albertanastasia** [comment]
. patch

**Pull request closed without merging**
