### PR TITLE
Locate all samples into one folder

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
I found it a bit confusing to have devworkspace and devfile samples have in different places, probably there is a motivation behind it but I missed that.
So, this PR locates all samples into one folder. It's devfile-support/samples folder.

### Alternative
I don't really understand the purpose of devfile-support folder and it may even make sense to move all samples into `/sample` directory in the project root.

### What issues does this PR fix or reference?
N/A

### Is your PR tested? Consider putting some instruction how to test your changes
Made sure that validate-samples script works as expected

#### Docs PR
https://github.com/devfile/docs/pull/8

### CODE REVIEW

**Comment by davidfestal** [comment]
Probably the purpose of having the devfile samples in a dedicated folder used to make more sense at the beginning of this repository, when the main purpose of this repository was to provide a Kubernetes API for the future Che DevWorkspace Controller, and also *derive* the  Devfile Json schema from it.

Now that the whole purpose of the repository is to define the main structure of the Devfile as well as associated K8S APIs, we might want to consider that the Devfile schema itself and DevWorkspace-related variants are just several ways to leverage the same core specification in different contexts.

What I'd recommend then, would be to have a single top-level folder `samples`, but still with one sub-folder for each type of yaml file:
- Devfile
- DevWorkspace
- DevWorkspaceTemplate

This would still allow the Devfile docs website to reference a folder with only devfiles, like it was until now: https://devfile.github.io/devfile/index.html#_devfile_v2_0_examples

**Review by davidfestal — CHANGES_REQUESTED** [review]
see my comment [here](https://github.com/devfile/api/pull/130#issuecomment-694185713)

**Comment by sleshchenko** [comment]
@davidfestal Could you please review it one more time, as well as docs related PR https://github.com/devfile/docs/pull/7 ?

**Review by amisevsk — APPROVED** [review]
Makes sense to me but I'd defer to David on if this is appropriate.

**Review by davidfestal — APPROVED** [review]
Both PRs approved (also the docs PR).
Thanks !

**Pull request merged**
