### PR TITLE
[wip] add RunOnDemand changes in devfile api. It is not ready to be merged.

### PR DESCRIPTION
**Pull request by rajibmitra**
### What does this PR do?:
This is the changes for RunOnDemand in container component. 

### Which issue(s) this PR fixes:
https://github.com/devfile/api/issues/852

### CODE REVIEW

**Review by amisevsk — CHANGES_REQUESTED** [review]
As discussed in the community call on June 20th, this is a breaking change and inverts the current default for container components.

**Comment by rajibmitra** [comment]
Thanks @amisevsk, any idea when we are planning to move to new API version ?

**Comment by rajibmitra** [comment]
thank you @yangcao77 for the clarification.

**Comment by l0rd** [comment]
@amisevsk I must admit that the name is confusing but `runOnDemand: false` means that the container gets started automatically, not on demand. That corresponds to current behavior. As you mention we don't want to change current behavior. This is also [explained here](https://github.com/devfile/api/issues/852#issuecomment-1152133647).

But, as mentioned by @yangcao77, on the 20th of June Devfile Cabal, we have discussed some different syntax and @kadel is looking at the proposal [but is currently on vacation](https://github.com/devfile/registry/pull/102#issuecomment-1165529425) so we need to be patient, and I don't think that there is any urgency.

@rajibmitra until we do not have an agreement on the syntax I would recommend you to:
- Set this PR as a draft and make it clear that it's not ready to be merged, the syntax will be changed
- Join the Cabal call on mondays, add topics if you have questions or want to discuss
- View at the recording of the [20th of June Devfile Cabal](https://drive.google.com/file/d/16n7QKmUvKziMUQgw6W1iIqn_TJzMmAGN/view?usp=sharing) (@elsony may be able to share it if that's blocked)
- Get familiar with the DevWorkspace operator and implement the controller changes related to this PR

**Comment by kadel** [comment]
Just making sure that everyone is aware of this: The updated proposal is at https://github.com/devfile/api/issues/852#issuecomment-1211928487
THis was discussed in this weeks devfile community call.

**Comment by maysunfaisal** [comment]
Closing this PR as its been WIP for 2 years.

**Pull request closed without merging**
