### PR TITLE
remove vscodetask and vscodelaunch, deprecate project.github

### PR DESCRIPTION
**Pull request by yangcao77**
Signed-off-by: Stephanie <yangcao@redhat.com>

### What does this PR do?
remove vscodetask and vscodelaunch, deprecate project.github
remove vacodetask & vacodelaunch related tests and sample devfiles

### What issues does this PR fix or reference?
#340 
#344

### CODE REVIEW

**Review by amisevsk — COMMENTED** [review]
I'm :+1: on the changes but I'm not sure they're fully complete -- on the CRDs side, this poses a bit of a problem in the conversion functions (as the removed command types obviously cannot be converted to `v1alpha2`). 

The easiest approach is to remove vscode-related tasks from the conversion tests -- I can help implement that if you would like.

**Comment by amisevsk** [comment]
I opened https://github.com/yangcao77/api/pull/1 into the PR branch to remove vscode tasks from conversion tests. 

It's also worth noting that this PR effectively removes the tasks from `v1alpha1` as well, since k8s clusters will store `v1alpha2`. Applying a `v1alpha1` DevWorkspace with vscode tasks will silently drop them from the object.

**Review by amisevsk — APPROVED** [review]
LGTM, we should get approval from @l0rd and/or @davidfestal before merge

**Comment by mmulholla** [comment]
Test updates LGTM

**Review by mmulholla — APPROVED** [review]
Tests LGTM

**Review by l0rd — APPROVED** [review]
I haven't tested this PR but this was discussed and agreed during last Cabal so +1 to merge.

**Review by elsony — APPROVED** [review]
/lgtm

**Pull request merged**
